version: '3.8'
services:
  todo-db:
    image: postgres:13
    volumes:
      - db-data:/etc/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
  freecodecamp:
volumes:
  db-data: